title: Ankit Bhatia
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  Avid high school coder and aspiring engineer.
author: Ankit Bhatia
email: ankbhatia19@gmail.com
avatar: #assets/images/avatar.jpg

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/ankbhatia19
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
